"use client"
import NavBar from '@/components/NavBar/NavBar';
import Footer from '@/components/Footer/Footer';
import { ReduxProvider } from './../redux/provider';
import { usePathname } from 'next/navigation'



export const metadata = {
  title: 'IZO',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  const pathname = usePathname()

  return (
    
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>{metadata.title}</title>
      </head>
      <body>
      {pathname!== '/' && <NavBar/>}
        <ReduxProvider>
          {children}
          </ReduxProvider>
       {pathname!== '/' && <Footer/>}

      </body>
    </html>
  )
}
